### ISSUE TITLE
Modelagem do Banco

### ISSUE THREAD

**Issue by lucasbezerra26** [SalesRyan/Mapa-Covid-19#2]
Modelagem: https://app.diagrams.net/#G1qEzdjY5iErSsDTBeTq7pjqf3O7kjr0-o

**Comment by spbdlelis** [comment]
Gráficos:
    Linhas:
        - Histórico de casos 
          confirmados
        - Histórico de óbitos
        - Histórico de ocupação de 
          leitos
        - Histórico da capacidade de 
          leitos

    Barras:
        - Óbitos com Comorbidades

    Pizza:
        - Distribuição de casos por sexo
        - Distribuição de óbitos por sexo
        - Ocupação de Leitos Clínicos
        - Ocupação de Leitos de UTI
        - Ocupação de Leitos de Est.
        - Ocupação de Leitos com 
          Resp.

   Tabelas:
      - Óbitos, Casos e Incidência por 
        cidade

**Comment by spbdlelis** [comment]
Gráficos:
    Linhas:
        - Histórico de casos confirmados
        - Histórico de óbitos
        - Histórico de ocupação de leitos
        - Histórico da capacidade de leitos

    Barras:
        - Óbitos com Comorbidades

    Pizza:
        - Distribuição de casos por sexo
        - Distribuição de óbitos por sexo
        - Ocupação de Leitos Clínicos
        - Ocupação de Leitos de UTI
        - Ocupação de Leitos de Estabilização
        - Ocupação de Leitos com Respiradores

   Tabelas:
      - Óbitos, Casos e Incidência por cidade
